# version: "3.9"
services:
  postgresql:
    image: postgres
    restart: always
    container_name: ${_POSTGRES_CONTAINER_NAME}
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${_POSTGRES_DB}
      POSTGRES_USER: ${_POSTGRES_USER}
      POSTGRES_PASSWORD: ${_POSTGRES_PASSWORD}
    ports:
      - ${_POSTGRES_PORT}:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data
     
    networks:
      - db-network
    

  pgadmin4:
    image: dpage/pgadmin4:7
    restart: always
    container_name: pgadmin4_container_my_app
    env_file:
      - ./.env
        
    environment:
      PGADMIN_DEFAULT_EMAIL: ${_PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${_PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - ${_PGADMIN_LISTEN_PORT}:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - db-network  
    depends_on:
      - postgresql
    
volumes:
  postgresql_data:
  pgadmin_data:

networks:
  db-network:
    driver: bridge